version: '3.1'

services:

    mongo:
        container_name: mongo
        volumes:
            - mongodb-vol:/data/db
        image: mongo:3.6.16-xenial
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root 
            MONGO_INITDB_ROOT_PASSWORD: password 
        ports:
            - 27017-27019:27017-27019
    mongo-express:
        container_name: mongo-express
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root 
            ME_CONFIG_MONGODB_ADMINPASSWORD: password 
volumes:
    mongodb-vol: